"""add sessions table

Revision ID: 9126dd80ec34
Revises: 512a269e0b08
Create Date: 2026-06-09 07:01:47.767141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9126dd80ec34'
down_revision: Union[str, None] = '512a269e0b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('inhale_seconds', sa.Integer(), nullable=True),
    sa.Column('exhale_seconds', sa.Integer(), nullable=True),
    sa.Column('cycles_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('mindfulness', 'body_scan', 'walking', 'loving_kindness', 'resonance_breathing', 'other')", name='ck_sessions_type'),
    sa.CheckConstraint('duration_seconds > 0', name='ck_sessions_duration_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_user_id_session_date', 'sessions', ['user_id', 'session_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_user_id_session_date', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
