"""breathing patterns + session fk

Revision ID: e533e31a65f9
Revises: 43d8e321a234
Create Date: 2026-06-09 08:42:00.140610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e533e31a65f9'
down_revision: Union[str, None] = '43d8e321a234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breathing_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('inhale_seconds', sa.Integer(), nullable=False),
    sa.Column('exhale_seconds', sa.Integer(), nullable=False),
    sa.Column('is_preset', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('exhale_seconds BETWEEN 1 AND 60', name='ck_bp_exhale_range'),
    sa.CheckConstraint('inhale_seconds BETWEEN 1 AND 60', name='ck_bp_inhale_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_breathing_patterns_user_id', 'breathing_patterns', ['user_id'], unique=False)

    # Seed global presets (user_id NULL = available to everyone), at the 2:3 ratio.
    op.execute(
        """
        INSERT INTO breathing_patterns
            (id, user_id, name, inhale_seconds, exhale_seconds, is_preset, created_at)
        VALUES
            (gen_random_uuid(), NULL, '6 bpm · balanced',  4,  6, true, now()),
            (gen_random_uuid(), NULL, '3 bpm · slow',      8, 12, true, now()),
            (gen_random_uuid(), NULL, '1.5 bpm · extended', 16, 24, true, now()),
            (gen_random_uuid(), NULL, '1 bpm · advanced',  24, 36, true, now())
        """
    )

    op.add_column('sessions', sa.Column('breathing_pattern_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_sessions_breathing_pattern_id',
        'sessions',
        'breathing_patterns',
        ['breathing_pattern_id'],
        ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    op.drop_constraint('fk_sessions_breathing_pattern_id', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'breathing_pattern_id')
    op.drop_index('ix_breathing_patterns_user_id', table_name='breathing_patterns')
    op.drop_table('breathing_patterns')
