"""add user username

Revision ID: fd668a5de4cc
Revises: 7f8fcb2e4b04
Create Date: 2026-06-09 10:31:29.878315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd668a5de4cc'
down_revision: Union[str, None] = '7f8fcb2e4b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', postgresql.CITEXT(), nullable=True))
    op.create_unique_constraint('uq_users_username', 'users', ['username'])


def downgrade() -> None:
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.drop_column('users', 'username')
